sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  "node"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - yarn add --dev coveralls codeclimate-test-reporter
script:
  - yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info
  - yarn e2e
